#!/usr/bin/env python

def build(bld):
  # use pdflatex to create documentation in pdf
  obj = bld.create_obj('tex', type='pdflatex')
  if bld.env()['debug']:
    obj.prompt = 0
  else:
    obj.prompt = 1
  obj.source = 'proposal.tex'

  # use latex to create documentation in dvi and ps (via dvi2ps)
  obj = bld.create_obj('tex', type='latex')
  if bld.env()['debug']:
    obj.prompt = 0
  else:
    obj.prompt = 1
  obj.source = 'proposal.tex'
  obj.outs = 'ps'
