#!/usr/bin/env python

def configure(conf):
  pass

def build(bld):
  obj = bld.create_obj('cpp', 'program')
  obj.find_sources_in_dirs('.')
  obj.uselib_local = 'yaml++'
  obj.includes = '..'
  obj.target = 'yaml++-demo'
