#!/usr/bin/env python

def build(bld):
  obj = bld.create_obj('cpp', 'program')
  obj.find_sources_in_dirs('. .. ../.. ../../test')

  # for some reason obj.source as filled-in by obj.find_sources_in_dirs doesn't
  # eliminate repeating slashes:  ..//main.cc ../..//file.hh
  # later we'll refer to ../main.cc, so it is essential we fix that.
  import re
  pattern = re.compile(r'//+')
  obj.source = [pattern.sub('/', src) for src in obj.source]

  obj.source.remove('../main.cc')
  obj.uselib = 'GTEST'
  obj.unit_test = 1
  obj.target = 'test'
